### ISSUE TITLE
Events channel extra information

### ISSUE THREAD

**Issue by dobrite** [wandenberg/nginx-push-stream-module#195]
Let me first say thank you for the fantastic module. Not only did it work out of the box it is also performing well in production.

I'm looking to move our current pusher presence channels over to the new "events channels". Is there a way to get more information from the messages posted to that channel? I'd like to be able to send arbitrary params (say, through the `extraParams` function) and have those show on the events channel. This would be items like `user_id`. 

I was planning on having a channel per person, in addition to the "main" channel, so that I could track this. I would include such information in the channel name and parse it out in some "events channel" daemon but I figured i'd just double check here before starting in.

Again, huge thanks for the great piece of software!

**Comment by wandenberg** [comment]
Hi @dobrite.
Currently we don't have this option to add data to the events channel message.
I'm preparing a way to add a "user label" to the subscriber and this information will be added to the subscriber event.
I'm calling it a label instead of an ID since the module will not be responsible to ensure that it be unique.
For now, I think the idea that use the channel name as user ID is doable.

**Comment by dobrite** [comment]
@wandenberg Great! Thanks for the quick reply and again, for the fantastic module!
