### ISSUE TITLE
Problem with installing nginx with  nginx-push-stream-module

### ISSUE THREAD

**Issue by kartikagarwal1993** [wandenberg/nginx-push-stream-module#198]
Following error is printed

make -f objs/Makefile install
make[1]: Entering directory '/home/kartik/nginx-1.0.5'
gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Wunused-function -Wunused-variable -Wunused-value -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../nginx-push-stream-module/src -I ../nginx-push-stream-module/include -I objs -I src/http -I src/http/modules -I src/mail \
	-o objs/addon/src/ngx_http_push_stream_module.o \
	../nginx-push-stream-module/src/ngx_http_push_stream_module.c
In file included from ../nginx-push-stream-module/src/ngx_http_push_stream_module.c:26:0:
../nginx-push-stream-module/include/ngx_http_push_stream_module.h:278:5: error: unknown type name ‘ngx_shmtx_sh_t’
     ngx_shmtx_sh_t                          messages_trash_lock;

**Comment by kartikagarwal1993** [comment]
The issue was solved when installed it with nginx 1.8.0

**Comment by kartikagarwal1993** [comment]
But on running configuration tests i recieve following error

nginx: [emerg] invalid event type "poll" in /home/kartik/nginx-push-stream-module/misc/nginx.conf:19

**Comment by wandenberg** [comment]
HI @kartikagarwal1993 
as write at readme the supported nginx versions are 1.2.0+, because of that worked when you moved from 1.0.5 to 1.8.0.
About the "poll" message you have to change to a event engine available at your system. For instance, kqueue to macos and epoll for linux.

Just a side note, the misc/nginx.conf file is used by me to develop the module and should not be used at production. Of course you can base on it to do your own configuration file.

**Comment by fasiha** [comment]
@kartikagarwal1993 just following up on what @wandenberg said, http://nginx.org/en/docs/events.html contains the full list of allowed event types. On Mac, the default `poll` isn't available, but `kqueue` is.
