### ISSUE TITLE
Dockerfile for simple up and running

### ISSUE THREAD

**Issue by mhndev** [wandenberg/nginx-push-stream-module#247]
Hi,
first of all thanks for the repository , It really fits my requirements,
It took me a whole day to install and start to using this nginx module,
I created a docker file which I suggest you to provide in your README or create your own official docker file.
thanks.
https://github.com/mhndev/docker-nginx-push-stream-module

**Comment by wandenberg** [comment]
Hi @mhndev ,
you are welcome. Thanks for use the project.

The process to compile this module is pretty much the same as any other Nginx module.
Did you take a look on [installation](https://github.com/wandenberg/nginx-push-stream-module#installation) instructions?

I notice that you are using a configuration very similar to that one in `misc` folder.
DO NOT use this file in a production environment. 
It is intended to be used on development only. It contains instructions like `master off;`, `daemon off;`, `postpone_output 1;`, `debug_points abort;` and others that make nginx works not on its maximum performance.
Of course you can use it as a reference / example.

About make a link to your project or provide an oficial Dockerfile I would suggest to do the same as the PPA package on issue #184, add the link on Wiki page.
The build of an nginx package is something that each project will require one different, different modules, specific OSs, ...
I prefer only to give instructions on how to build and how to use it, and let each one do their own tools, since the process is not that complicated.

**Comment by mhndev** [comment]
thanks fr your quick answer , my problem was events : poll , which I changed it to epoll, and now everything works well,
and also thanks for your advice , I'll change my nginx.conf for production.
I added this docker file to wiki .
