### ISSUE TITLE
use okhttp3 websocket return 1005

### ISSUE THREAD

**Issue by 1371030** [wandenberg/nginx-push-stream-module#253]
use okhttp3
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/WebSocketEcho.java

use this sample.
change ws to ws://127.0.0.1 
 wait 10SECONDS， websocket return 1005

**Comment by wandenberg** [comment]
Hi @1371030 if you are using the `WebSocketEcho.java` example only changing the ws address the behaviour is as expected.
This sample send 3 messages and then close the connection as you can see [here](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/WebSocketEcho.java#L30).
The close frame tell to the server that the client don't want to keep the connection open, and the server closes the connection on its side.
The 1005 code that you received is a code on the okhttp3 client, indicating that the server closed the connection without specifying a reason ([check here](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/ws/WebSocketProtocol.java#L96)). Which is totally OK on this case, since the client already know the reason _it asked to close the connection_.

**Comment by 1371030** [comment]
thanks,nginx-push-stream-module very nice!
